### ISSUE TITLE
Vignette?

### ISSUE THREAD

**Issue by dktanwar** [andreamrau/padma#1]
Where can I find a Vignette for the package?

**Comment by andreamrau** [comment]
Great question -- this has been on my to-do list, I'll bump it up and try to get it ready ASAP.

**Comment by andreamrau** [comment]
I finally got around to getting a first draft of the vignette up -- thanks for your patience. 

https://htmlpreview.github.io/?https://github.com/andreamrau/padma/blob/master/doc/padma.html
